server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: reservation-access
  config:
    import: optional:configserver:http://config-service:8888

management:
  endpoints:
    web:
      exposure:
        include: health,info

spring.lifecycle:
  timeout-per-shutdown-phase: 20s