server:
  port: 8080

spring:
  application:
    name: edge-service
  cloud:
    gateway:
      routes:
        - id: room-manager
          uri: http://room-manager:8080
          predicates:
            - Path=/rooms/**
        - id: reservation-manager
          uri: http://reservation-manager:8080
          predicates:
            - Path=/reservations/**

management:
  endpoints:
    web:
      exposure:
        include: health,info
