server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: reservation-manager
  config:
    import: optional:configserver:http://config-service:8888
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: health,info

spring.lifecycle:
  timeout-per-shutdown-phase: 20s
