apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-access
spec:
  replicas: 1
  selector:
    matchLabels:
      app: room-access
  template:
    metadata:
      labels:
        app: room-access
    spec:
      containers:
        - name: room-access
          image: room-access
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/db

            - name: SPRING_DATASOURCE_USERNAME
              value: postgres

            - name: SPRING_DATASOURCE_PASSWORD
              value: password