apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: room-manager
  template:
    metadata:
      labels:
        app: room-manager
    spec:
      containers:
        - name: room-manager
          image: room-manager:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes