server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: room-manager
  config:
    import: optional:configserver:http://config-service:8888

management:
  endpoints:
    web:
      exposure:
        include: health,info

spring.lifecycle:
  timeout-per-shutdown-phase: 20s

resilience4j:
  circuitbreaker:
    instances:
      roomManager:
        sliding-window-size: 10
        failure-rate-threshold: 30
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, circuitbreakers
