server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: edge-service
  config:
    import: optional:configserver:http://config-service:8888
  redis:
    host: redis
    port: 6379
  cloud:
    gateway:
      routes:
        - id: room-manager
          uri: http://room-manager:8080
          predicates:
            - Path=/rooms/**
        - id: reservation-manager
          uri: http://reservation-manager:8080
          predicates:
            - Path=/reservations/**

management:
  endpoints:
    web:
      exposure:
        include: health,info



spring.lifecycle:
  timeout-per-shutdown-phase: 20s


